service: GraphTV-Serverless

custom: ${file(serverless.${opt:stage}.yml)}

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
      Resource: { "Fn::Join" : ["", ["arn:aws:dynamodb:", { "Ref": "AWS::Region" }, ":", { "Ref": "AWS::AccountId" }, ":table/GraphTV-Ratings-", "${opt:stage}" ] ] }
      # The above line will need to change once we re-create the database for each stage,
      # right now the data is only in prod.

package:
  include:
    - handler.py
    - graphtv/**

functions:
  ShowsRatings:
    handler: handler.get_ratings
    memorySize: 128
    timeout: 10
    environment:
      RATINGS_TABLE: GraphTV-Ratings-${opt:stage}

resources:
  Resources:
    ExecuteShowsRatings:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt: [ ShowsRatingsLambdaFunction, Arn ]
        Action: 'lambda:InvokeFunction'
        Principal: apigateway.amazonaws.com
        SourceArn:
          Fn::Join:
            - ''
            - - 'arn:aws:execute-api:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':${self:custom.api_gateway_id}/*/GET/shows/*/ratings'
